# Embeds a compiled SPIR-V binary (.spv) into a C++ header as a byte array, so the built
# pipeline_gpu/pipeline_cpu executables never need to locate a loose .spv file at runtime.
# Copy of lib/aff3ct/lib/streampu/cmake/Vulkan/embed_spirv.cmake, namespaced for this project
# instead of StreamPU's own spu::sp_vulkan (that script isn't installed alongside StreamPU's
# headers/libs, only usable from within the StreamPU source tree, so it can't be reused directly
# by a project that only sees the installed StreamPU package).
#
# Usage: cmake -DSPV_FILE=<path> -DOUT_FILE=<path> -DSYMBOL=<name> -P embed_spirv.cmake

if(NOT DEFINED SPV_FILE OR NOT DEFINED OUT_FILE OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "embed_spirv.cmake requires SPV_FILE, OUT_FILE and SYMBOL to be defined")
endif()

file(READ "${SPV_FILE}" spv_hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," spv_bytes "${spv_hex}")

file(WRITE "${OUT_FILE}"
"// Auto-generated by cmake/embed_spirv.cmake from ${SPV_FILE} -- do not edit.
#pragma once
#include <cstddef>

namespace pipeline_vulkan_shaders
{
static constexpr unsigned char ${SYMBOL}[] = { ${spv_bytes} };
static constexpr size_t ${SYMBOL}_size = sizeof(${SYMBOL});
}
")
